// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PersonalAccountant.Web.PAEntity;
using System;

namespace PersonalAccountant.Web.Migrations
{
    [DbContext(typeof(PADatabaseContext))]
    [Migration("20180726094836_Mig4")]
    partial class Mig4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.Accounts", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName")
                        .IsRequired();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.ExpenseCategory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("ID");

                    b.ToTable("ExpenseCategory");
                });

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.ExpenseHistory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<Guid>("ExpenseCategoryID");

                    b.Property<string>("Remarks");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("ID");

                    b.HasIndex("ExpenseCategoryID");

                    b.ToTable("ExpenseHistory");
                });

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.IncomeCategory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("ID");

                    b.ToTable("IncomeCategory");
                });

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.IncomeHistory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<Guid>("IncomeCategoryID");

                    b.Property<string>("Remarks");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("ID");

                    b.HasIndex("IncomeCategoryID");

                    b.ToTable("IncomeHistory");
                });

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.ExpenseHistory", b =>
                {
                    b.HasOne("PersonalAccountant.Web.PAEntity.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PersonalAccountant.Web.PAEntity.IncomeHistory", b =>
                {
                    b.HasOne("PersonalAccountant.Web.PAEntity.IncomeCategory", "IncomeCategory")
                        .WithMany()
                        .HasForeignKey("IncomeCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
